spring.application.name=weather-egg-api

# Database connectivity (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/weather_egg_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0